### ISSUE TITLE
Support JDK 8 on platforms other than Oracle

### ISSUE THREAD

**Issue by carmstrong** [agileorbit-cookbooks/java#155]
Thanks to #147, the cookbook installs JDK 8 on Oracle. OpenJDK 8 builds have not yet been pushed to the various platform repositories, which means we don't yet have a method for installation on other platforms. Should we consider an alternative package repository for each platform? #149 suggests one for Ubuntu, but I think maintaining cookbook logic for each platform would become cumbersome. 

I'd like to add support for JDK 8 sooner rather than later, so we can prepare v2.0.0 of the cookbook which will drop support for JDK 6 and install JDK 7 by default.

**Comment by hntd187** [comment]
Amazon linux also has openjdk available.
````
Loaded plugins: priorities, update-motd, upgrade-helper
========================================================================================================== N/S matched: java-1.8 ===========================================================================================================
java-1.8.0-openjdk.x86_64 : OpenJDK Runtime Environment
java-1.8.0-openjdk-demo.x86_64 : OpenJDK Demos
java-1.8.0-openjdk-devel.x86_64 : OpenJDK Development Environment
java-1.8.0-openjdk-headless.x86_64 : OpenJDK Runtime Environment
java-1.8.0-openjdk-javadoc.noarch : OpenJDK API Documentation
java-1.8.0-openjdk-src.x86_64 : OpenJDK Source Bundle
````

**Comment by derekbelrose** [comment]
Has there been any decision made about this?  Right now I'm running a forked version using the patch that is mentioned in this issue.
