### ISSUE TITLE
Add boolean toggle to download unlimited strength JCE policy files

### ISSUE THREAD

**Issue by themasterchef** [agileorbit-cookbooks/java#199]
As anyone who's using Jruby / Rails will know, when you invoke any form of crypto operation through your Rails server on a vanilla install of Oracle JVM, you will normally get the following error:

"OpenSSL::Cipher::CipherError: Illegal key size: possibly you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for your JRE"

Running on a machine with an Oracle JVM provisioned using this cookbook is no exception, as the cookbook doesn't seem to do anything about these files when it runs the oracle installer.

Would it be possible to add a boolean toggle for the cookbook to automate obtaining these JCE jar files and installing them in the right place? It would default to false to stay in line with US export policy. I envisage it working much like the existing "java" => "oracle" => "accept_oracle_download_terms", so it could be called something like "java" => "oracle" => "accept_unlimited_strength_jce_download_terms". 

I don't know if the other JVM variants (e.g. IBM's one) also have this restriction, but if they do, probably best to add it as a provider-specific option in each case, rather than a blanket parameter at the top level, because OpenJDK just seems to turn on unlimited strength crypto by default.

For additional brownie points, when the toggle is set to true, you could log out one of those scary legalese warnings saying that the user has explicitly chosen to turn on unlimited strength crypto, which may put them in violation of US export policy.

**Comment by bassrock** [comment]
:+1: Also need this!

**Comment by erichelgeson** [comment]
This is in 1.31.0 released today.
