### ISSUE TITLE
Cautionary tale: Chef 12.0.0 and JDK url

### ISSUE THREAD

**Issue by nefilim** [agileorbit-cookbooks/java#226]
Really just putting this here in case others run into the same nasty surprise. I updated a production Cloud Formation stack which for some reason recreated an autoscale group (and all the nodes). The new nodes picked up Chef 12.0.0. 
I also specified my own JDK 7 URL (7u72) and everything has been working just fine until today. I believe this issue that has been fixed/introduced with Chef 12.0.0 is at play here: 

https://tickets.opscode.com/browse/CHEF-4647

I never specified a checksum, I assume the java cookbook used it's own default. Now since remote_file  actually checked the checksum, it suddenly started failing. 

Took a while to root cause because of a few red herrings. Perhaps highlights some of the dangers with the chef default/overridable attributes (don't think it's possible to check if one was overridden others in the group must also be?). Maybe add a big fat warning about this in the documentation?

**Comment by erichelgeson** [comment]
Using the latest chef client 12.0.3 there were no issues and it seems that windows issue has been addressed.
