### ISSUE TITLE
Unable to install Oracle Java 8 update 25 on windows 7

### ISSUE THREAD

**Issue by koyadume** [agileorbit-cookbooks/java#227]
This is follow up of #182. Not sure if anyone has successfully installed Oracle Java on a windows (7) box using this cookbook but this is not working for me.

I was able to install Oracle Java on my windows box using windows cookbook. I blogged about it here -
http://pistonportal.wordpress.com/2014/06/18/managing-java-on-windows-using-chef/

However this is not working with latest version of Chef client for windows. 

I upgraded chef client to 12.0.1 and java cookbook to 1.29.0 and created a json file for a role -
```json
{
  	"name" : "jdk",
  	"description" : "JDK",
  
  	"json_class" : "Chef::Role",
	"chef_type" : "role",
  
  	"default_attributes" : {
		"java" : {
			"install_flavor" : "oracle",
			"java_home" : "D:\\Java",
			"jdk_version" : "8",
			"oracle" : {
				"accept_oracle_download_terms" : "true"
			}
		}
  	},

	"run_list": [
		"recipe[java]"
	]
}
``` 
After running ```chef-solo -c .chef\solo.rb -j .chef\node.json``` I am seeing following output -
```
Starting Chef Client, version 12.0.1
Compiling Cookbooks...
Converging 4 resources
Recipe: java::set_java_home
  * ruby_block[set-env-java-home] action run
    - execute the ruby block set-env-java-home
  * directory[/etc/profile.d] action create
    * Parent directory /etc does not exist, cannot create /etc/profile.dC:/opscode/chef/embedded/apps/chef/lib/chef/formatters/err
or_inspectors/resource_failure_inspector.rb:66: warning: invalid subexp call
C:/opscode/chef/embedded/apps/chef/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb:66: warning: invalid Unicode
 Property \p

    ================================================================================
    Error executing action `create` on resource 'directory[/etc/profile.d]'
    ================================================================================

    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    Parent directory /etc does not exist, cannot create /etc/profile.d

    Resource Declaration:
    ---------------------
    # In devops-piston-windows\cookbooks\java\recipes\set_java_home.rb

      1: # Author:: Joshua Timberman (<joshua@opscode.com>)
      2: # Cookbook Name:: java

    Compiled Resource:
    ------------------
    # Declared in devops-piston-windows\cookbooks\java\recipes\set_java_home.rb:26:in `
from_file'

    directory("/etc/profile.d") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/etc/profile.d"
      cookbook_name :java
      recipe_name "set_java_home"
      mode 493
    end


Running handlers:
[2014-12-12T21:10:10+05:30] ERROR: Running exception handlers
Running handlers complete
[2014-12-12T21:10:10+05:30] ERROR: Exception handlers complete
[2014-12-12T21:10:10+05:30] FATAL: Stacktrace dumped to devops-piston-windows/.chef/che
f-stacktrace.out
Chef Client failed. 1 resources updated in 12.354027 seconds
[2014-12-12T21:10:10+05:30] FATAL: Chef::Exceptions::EnclosingDirectoryDoesNotExist: directory[/etc/profile.d] (java::set_java_hom
e line 26) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc does not exist, cannot create /et
c/profile.d
```

It seems that cookbook is not detecting platform (windows, linux etc) correctly as evident from the directory path (/etc) its trying to locate. Also in my many years with Java I never heard about anything called windows Java. There are only two flavors (OpenJDK and Oracle) of Java which are mostly used by Java developers. IBM Java is shipped with IBM Java based products and I have never seen developers using IBM Java with non IBM products. 

I believe you should introduced an extra parameter for specifying platform unless chef can detect it automatically. Also you may drop windows value from possible values for install_flavor attribute.

**Comment by erichelgeson** [comment]
Your specific error is you are not providing a URL to pull java from, so it is failing. https://github.com/agileorbit-cookbooks/java/blob/master/recipes/windows.rb#L29. We can grab the file from Oracle for *nix because we have utilities like curl to send the right headers/etc. Remote file might work again now for windows, though haven't tried.

I have installed in on windows before, but to be honest the tooling at the time is quite bad, test kitchen, licensing windows, etc. It has gotten better but still not great. Due to that there are not tests for the windows platform. If you've made progress on that front, pull requests welcome.

Also you're using Chef 12. I haven't tested chef12 on any platforms, there was an issue with the windows resource conflicting with the windows cookbook in 12.0.0/1 I believe.

Sorry for replying 20 days later, I honestly missed your reply.

**Comment by koyadume** [comment]
Actually I am a Java developer who is using chef to automate local environment setup. I don't have good understanding of chef at code level and ruby in particular. 

I don't think I can debug these kind of problems myself without having good knowledge of ruby. Unfortunately I have other priorities and so can't work in this direction.

I have moved to powershell as using chef on my windows 7 box was becoming painful day by day. I may come back here once I start using chef on my linux desktop. 

Finally thank you for your response. Wish you a very happy new year.

**Comment by erichelgeson** [comment]
Glad you got some automation working for you. Chef does have some powershel integration as well if you're ever interested in the future - http://blogs.msdn.com/b/powershell/archive/2014/07/29/chef-with-powershell-dsc-now-public.aspx
