### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by tas50** [agileorbit-cookbooks/java#229]
It would be really awesome to get OS X support here for jenkins slave node setup

**Comment by danieljimenez** [comment]
Actually the best way to do this on Mac OS is simply `homebrew_cask 'java`.

**Comment by danieljimenez** [comment]
Apologies, as I'm new to Chef, but what's the best/cleanest way to insert a dependency into the project? Homebrew requires "depends homebrew" in metadata.rb (no entry in Berksfile required).

**Comment by erichelgeson** [comment]
Initial support in now.
