### ISSUE TITLE
Please change the default version to 7

### ISSUE THREAD

**Issue by gtabaresworskshare** [agileorbit-cookbooks/java#232]
Java 6 is mostly out of support - Can we please change the default version to 7?

It will make more sense than having to keep your own config.

**Comment by erichelgeson** [comment]
Java 6 was the default when this was released. Version 2 of this cookbook will have java7 as the default. If we change it in v1, it would break many people. Check out the wiki page for the V2 roadmap. https://github.com/agileorbit-cookbooks/java/wiki/Roadmap

You should just be able to override an attribute to get java 7 in a recipe/role/environment. That isn't too much of a burden.
