### ISSUE TITLE
Document how to override attribute

### ISSUE THREAD

**Issue by spuder** [agileorbit-cookbooks/java#238]
It would be nice if the readme provided a clear example of how to override an attribute. If you are new to chef, then it is difficult to get this cookbook working. 

For example, how do you install java 7 on ubuntu 14.04? Neither of the following overrides work. 

![screenshot 2015-01-28 16 42 30](https://cloud.githubusercontent.com/assets/242382/5949717/0ce4e358-a70e-11e4-93de-08eb23e88c13.png)
![screenshot 2015-01-28 16 49 45](https://cloud.githubusercontent.com/assets/242382/5949716/0ce4d8cc-a70e-11e4-81b0-10a91ab9bf6a.png)

**Comment by erichelgeson** [comment]
Hi @spuder, welcome to the world of chef! Hope your stay is delightful.

The README does have many examples of how to set attributes for this cookbook. There are a lot of different ways to do this and the README of the java cookbook isn't the place to describe this chef concept.

It looks like you're trying to create a role. A role can be in many formats (though stored in chef-server as json, so it looks like the UI only accepts json). The README examples are in ruby. 

You can pretty easily translate the ruby to json:
Ruby
```ruby
  "java" => {
    "install_flavor" => "oracle",
    "jdk_version" => "7",
    "oracle" => {
      "accept_oracle_download_terms" => true
    }
```
JSON - 
```json
{
  "java": { 
    "install_flavor": "oracle",
    "jdk_version": 7,
    "oracle": {
      "accept_oracle_download_terms": true
    }
  }
}
```
(Just did this by hand but should be right :) )

More info on roles and attributes:
https://docs.chef.io/roles.html
https://docs.chef.io/attributes.html

Check out the chef mailing list, irc channel, Learning Chef book, etc for more help along your journey.

HTH
