### ISSUE TITLE
Berkshelf fails with "undefined method 'source_url'"

### ISSUE THREAD

**Issue by jeffjcrowe** [agileorbit-cookbooks/java#240]
This error has started appearing in Berkshelf 3.1.3 on AWS OpsWorks since this commit:
https://github.com/agileorbit-cookbooks/java/commit/f7bd0449afb75cac6b88ade173fd7b3f92e73155

[2015-02-10T20:42:28+00:00] ERROR: ruby_block[Install the cookbooks specified in the Berksfile and their dependencies] (/var/lib/aws/opsworks/cache.stage1/cookbooks/opsworks_berkshelf/providers/runner.rb line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '47'
---- Begin output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----
STDOUT: Resolving cookbook dependencies...
Fetching 'alertlogic' from source at alertlogic
Fetching 'apt' from git://github.com/opscode-cookbooks/apt.git (at master)
Fetching 'build-essential' from git://github.com/opscode-cookbooks/build-essential.git (at master)
Fetching 'java' from git://github.com/agileorbit-cookbooks/java.git (at master)
STDERR: Ridley::Errors::FromFileParserError Could not parse `/tmp/d20150210-4455-n04k0q/metadata.rb': undefined method `source_url' for #<Ridley::Chef::Cookbook::Metadata:0x007f93582e0f70>
---- End output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----

**Comment by skazzyy** [comment]
I didn't realize those were introduced in Chef 12 and not backwards compatible... is there a new version of Berkshelf that works?

https://github.com/chef/chef/blob/9760d40e2f924e8fdd5b42760c4fb775572fb777/RELEASE_NOTES.md#new-cookbook-metadata-attributes-for-supermarket

**Comment by jeffjcrowe** [comment]
Unfortunately OpsWorks only support up to Chef 11.10 and Berkshelf 3.1.3

http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html#workingcookbook-chef11-10-berkshelf

**Comment by erichelgeson** [comment]
I hope this is your non-prod stack in OpsWorks if you're deploying off master :) I'd recommend forking or deploying off Tag'd releases to avoid unexpected/tested changes in your environment.

Cause was the merge today of #239. I reverted that merge and pushed it up. May want to open an issue with berkshelf this.

**Comment by jeffjcrowe** [comment]
Yeah this is in my dev stack. Thanks for the quick response!
