### ISSUE TITLE
Java can't target multiple platforms due to install_flavor issue

### ISSUE THREAD

**Issue by dhoer** [agileorbit-cookbooks/java#242]
Setting install_flavor to 'oracle' for linux installs results in windows installs failing.  

Example; this setting:
```
"java": {
  "install_flavor": "oracle",
  "jdk_version": "7",
  "oracle": {
      "accept_oracle_download_terms": true
  }
  "windows": {
    "url": "https://s3.amazonaws.com/mybucket/jdk-7u75-windows-i586.exe",
    "checksum": "b916d1724e29df886fc0858b72547212"
  }
}
```
will result in this error on windows platform:
```
[2015-02-16T18:40:04+00:00] INFO: Processing ruby_block[set-env-java-home] action run (java::set_java_home line 19)
[2015-02-16T18:40:04+00:00] INFO: Processing directory[/etc/profile.d] action create (java::set_java_home line 26)

================================================================================
Error executing action `create` on resource 'directory[/etc/profile.d]'
================================================================================

Chef::Exceptions::EnclosingDirectoryDoesNotExist
------------------------------------------------
Parent directory /etc does not exist, cannot create /etc/profile.d

Resource Declaration:
---------------------
# In c:/chef/cache/cookbooks/java/recipes/set_java_home.rb

26: directory "/etc/profile.d" do
27:   mode 00755
28: end
29:
```

**Comment by erichelgeson** [comment]
You do not need to specify install_flavor on windows, it will detect that for you.

See https://github.com/agileorbit-cookbooks/java#attributes

and previous discussion -
https://github.com/agileorbit-cookbooks/java/issues/227#issuecomment-67027303

I may add a section on windows with a full example in the readme so it is clear.
Thanks,

**Comment by dhoer** [comment]
I use the same environment for linux installs.

**Comment by erichelgeson** [comment]
I see your point now, but the solution is to set `java.install_flavor` at the correct time for the correct platforms. Maybe leave that out of your environment and use roles?

**Comment by dhoer** [comment]
That seems to be an anti-pattern for Chef multiple platform support.  Maybe changing https://github.com/agileorbit-cookbooks/java/blob/master/attributes/default.rb#L37 to be 
```
node.set['java']['install_flavor'] = "windows"
```
Might work?

**Comment by dhoer** [comment]
The work around was to not set install_flavor and download java tar from s3 bucket.

**Comment by dhoer** [comment]
Maybe the best fix is to add the following line to the top of `recipes/default.rb`:
```
node.set['java']['install_flavor'] = 'windows' if platform_family?('windows')
```

What are your thoughts on this?

**Comment by dhoer** [comment]
I see this is closed.  Can this be reopened?
