### ISSUE TITLE
last commit broke libraries/helpers.rb

### ISSUE THREAD

**Issue by clshrock** [agileorbit-cookbooks/java#244]
Chef is not a module

**Comment by christopher5106** [comment]
Same error for me

**Comment by erichelgeson** [comment]
I've reverted the commit. @someara can you please PR instead of pushing to master so it can run through travis/have a second set of eyes. Thanks!

**Comment by someara** [comment]
sorry. java cookbook was left over in my directory I was doing semi-automated bit flipping on =)

**Comment by erichelgeson** [comment]
Automation :facepunch: It happens, glad we have people integrating with master. Also wonder why travis didn't email me that master failed...

**Comment by someara** [comment]
remote updated to my personal fork. wont happen again
-s

**Comment by christopher5106** [comment]
great thanks
