### ISSUE TITLE
Add end-of-line to jdk.sh and jdk_home.ssh files in /etc/profile.d/.

### ISSUE THREAD

**Issue by nkadel-skyhook** [agileorbit-cookbooks/java#249]
On CentOS and RHEL based systems, the "/etc/profile.d/jdk.sh" lacks an end-of-line. This makes it confusing to read, although it does not break using a 'source' command as it stands.

**Comment by erichelgeson** [comment]
I'm not sure why that would be confusing to read.

**Comment by nkadel-skyhook** [comment]
Because if you "cat" it, your next prompt shows up on the end of the file, instead of on a separate line. It also causes "less" and "emacs" to complain about the missing EOL.

For example, see below operation of "cat" against sh files without a trailing EOL.

[nkadel@hostname.example.com ~]$ cat /etc/profile.d/jdk.sh
export JAVA_HOME=/usr/java/default[nkadel@hostname.example.com ~]$
