### ISSUE TITLE
support for S3 query string authentication url

### ISSUE THREAD

**Issue by khoan** [agileorbit-cookbooks/java#254]
When hosting jdk on S3, java.jdk.< version >.< arch >.url doesn't support query string authentication style. More info at: http://s3.amazonaws.com/doc/s3-developer-guide/RESTAuthentication.html

**Comment by fletchowns** [comment]
Is your node on EC2? If so I think you can use an IAM role to provide access to the S3 bucket.

Or maybe try the [aws_s3_file](https://github.com/opscode-cookbooks/aws#aws_s3_file) LWRP from the aws cookbook to download it.

**Comment by khoan** [comment]
hum...not sure how to incorporate aws_s3_file, and IAM into downloading oracle flavour
https://github.com/agileorbit-cookbooks/java/blob/master/recipes/oracle.rb#L53

I'll explore the suggested further, thanks.

**Comment by fletchowns** [comment]
You basically use aws_s3_file to download the oracle jdk yourself, and the URL you feed into this java cookbook should point to that file you already downloaded using file://

See this for more details:
https://github.com/burtlo/ark/pull/54

**Comment by khoan** [comment]
thanks for the pointer, makes sense.

**Comment by erichelgeson** [comment]
I'd accept a PR that gave the flexibility, but IAM roles are really the way to go. 
Also this work around is fine approach too

**Comment by khoan** [comment]
nice! @erichelgeson
