### ISSUE TITLE
windows installer with custom java_home fails

### ISSUE THREAD

**Issue by joelwilson** [agileorbit-cookbooks/java#257]
It seems that the [additional options](https://github.com/agileorbit-cookbooks/java/blob/master/recipes/windows.rb#L58) which are passed to the `windows_package` resource if the `java => java_home` attribute is set do not work - at least not with the Java 8 update 40 installer on Windows 2012 R2. Perhaps they worked with the Java 7 installer.

The recipe's generated command to run the installer passes these switches (with `node['java']['java_home']` set to `'C:\Program Files\Java'`):

    /s /v"/qn INSTALLDIR=\"C:\Program Files\Java\""

I could not get these switches to work even when manually executing the command with every permutation I could come up with.

I was, however, able to get the installer working silently after reviewing [Oracle's Documentation for silent install](https://www.java.com/en/download/help/silent_install.xml). These switches work:

    /s INSTALLDIR="C:\Program Files\Java"

**Comment by manuelmazzuola** [comment]
+1

**Comment by joshburt** [comment]
This has been submitted as a smaller delta to accomplish the change: https://github.com/agileorbit-cookbooks/java/pull/273
