### ISSUE TITLE
ubuntu 14.04 install fails on link("/usr/lib/jvm/default-java")

### ISSUE THREAD

**Issue by evilbulgarian** [agileorbit-cookbooks/java#260]
This directory ( /usr/lib/jvm )  does not exist on a new ubuntu 14.04 server install. Please fix cookbook to check for that dir and create it before creating a symlink there maybe?

**Comment by evilbulgarian** [comment]
directory "/usr/lib/jvm" do 
    owner 'root'
    group 'root'
    mode '0755'
    action :create
end

**Comment by erichelgeson** [comment]
It doesn't fail in test kitchen with the provide params, can you show me a failing test scenario? https://github.com/agileorbit-cookbooks/java/blob/master/.kitchen.yml#L15-L20

**Comment by evilbulgarian** [comment]
Recipe: java::default_java_symlink
  * link[/usr/lib/jvm/default-java] action create
================================================================================
Error executing action `create` on resource 'link[/usr/lib/jvm/default-java]'
================================================================================


Errno::ENOENT
-------------
No such file or directory - (/usr/local/java, /usr/lib/jvm/default-java)


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/java/recipes/default_java_symlink.rb

 16: link '/usr/lib/jvm/default-java' do
 17:   to node['java']['java_home']
 18:   not_if { node['java']['java_home'] == '/usr/lib/jvm/default-java' }
 19: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/java/recipes/default_java_symlink.rb:16:in `from_file'

link("/usr/lib/jvm/default-java") do
  provider Chef::Provider::Link
  action :create
  retries 0
  retry_delay 2
  to "/usr/local/java"
  link_type :symbolic
  target_file "/usr/lib/jvm/default-java"
  cookbook_name "java"
  recipe_name "default_java_symlink"
  not_if { #code block }
end



[2015-04-24T17:13:53+00:00] ERROR: Running exception handlers
[2015-04-24T17:13:53+00:00] ERROR: Exception handlers complete
[2015-04-24T17:13:53+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 4 resources updated
[2015-04-24T17:13:53+00:00] ERROR: link[/usr/lib/jvm/default-java] (java::default_java_symlink line 16) had an error: Errno::ENOENT: No such file or directory - (/usr/local/java, /usr/lib/jvm/default-java)
[2015-04-24T17:13:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by sabishop** [comment]
I'm still seeing this issue when installing the oracle jdk on Unbuntu 14.04.

Creating the directory `/usr/lib/jvm/default-java` allows the installation to succeed.

**Comment by erichelgeson** [comment]
The dir is created by `java_ark` here - https://github.com/agileorbit-cookbooks/java/blob/master/providers/ark.rb#L112 

And running on 14.04.2 latest with the last release it creates it correctly: 
```
Recipe: java::oracle
         * java_ark[jdk] action install
           - create dir /usr/lib/jvm and change owner to root:root
```

Can you please provide a complete example cookbook that you see this error using a public vagrant box? This is working as far as I can tell without more information.
