### ISSUE TITLE
Missing version 1.30.0

### ISSUE THREAD

**Issue by maoueh** [agileorbit-cookbooks/java#262]
This is not a big problem per se, but I wanted to report it nonetheless.

It seems there was a problem on the latest release because version 1.30.0 has been skipped and is not available on the supermarket. I made the mistake because I looked at the changelog version. 

Here a recap:
 * Commit says released version 1.31.0
 * File `metadata.rb` has been updated to version 1.31.0
 * Changelog has been updated to version 1.30.0
 * Supermarket release is at version 1.31.0 and does not have a 1.30.0 version.

Feel free to close if you think no further actions should be made for this issue.

Regards,
Matt

**Comment by erichelgeson** [comment]
Your correct, typo. I'll fix it up for next release.
