### ISSUE TITLE
ark_java fails when tar is not installed

### ISSUE THREAD

**Issue by ringods** [agileorbit-cookbooks/java#263]
The Docker image `centos:6` doesn't seem to have `tar` installed by default. When running the `java` cookbook, the `java_ark` provider fails on the extraction part. Should it check for the availability of `tar` and install the package when needed?

Side question: the docs mention that `java_ark` is deprecated in favor of the `ark` cookbook, but I don't see any dependency yet. Is this future work?

**Comment by erichelgeson** [comment]
Yes I suppose that'd make sense as it's a hard dependency when using that provider. If you'd like to take a stab at putting that in and making a PR great! If not let me know and I'll get it in next release.

To your side question - there's no reason to use the `java_ark` resource directly when there's the `ark` cookbook.

**Comment by patcon** [comment]
Submitted a PR to install tar package right before java_ark resource is used
