### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by thoutenbos** [agileorbit-cookbooks/java#274]
Good day,

Would you be able to release a new version of the cookbook in the supermarket? Some interesting additions have been done since the release of v1.31.0 and it would be nice to have them in a new stable version.

Thanks!

Best,
Thijs

**Comment by dhoer** [comment]
:+1:

**Comment by thoutenbos** [comment]
@erichelgeson would this be possible?

**Comment by zlangbert** [comment]
+1

**Comment by dhoer** [comment]
@thoutenbos @zlangbert I'm thinking about releasing a new java cookbook called java_se.  All it would do is install oracle jdk 8x on linux, mac os x, and windows.  Is that something you would be interested in?

**Comment by zlangbert** [comment]
@dhoer Personally I'm looking to install openjdk 8 not oracle, which is why I was hoping for an update to this

**Comment by dhoer** [comment]
@zlangbert Thanks, I'm looking for mac and windows installer for oracle jdk.

**Comment by erichelgeson** [comment]
1.35.0 released.
