### ISSUE TITLE
can a new version be release with the openjdk 8 ppa support

### ISSUE THREAD

**Issue by ramonskie** [agileorbit-cookbooks/java#300]
there was a pull request merged https://github.com/agileorbit-cookbooks/java/pull/286
and i would really like to use this version

so is it possible to release it to the chef supermarket?

**Comment by johnbellone** [comment]
:+1:

**Comment by remiuz** [comment]
Yes it would be very nice if we could use JDK 8 version from Open JDK ! The repo from Oracle is often not available and it will fix my chef deployment problems.

**Comment by tas50** [comment]
:+1:

**Comment by erichelgeson** [comment]
v1.36.0 released.
