### ISSUE TITLE
Windows default recipe install not idempotent

### ISSUE THREAD

**Issue by glennmate** [agileorbit-cookbooks/java#312]
If the java::default recipe is installed by default (simply using include java::default as the recipe) in Chef I find that the node will attempt to reinstall the software (Java) every 30 minutes. This hangs the install, which then causes conflicts on the next chef-client run (see below). We are using the default recipe on Server 2012 R2 platform. Getting the following log error entries: 

Log Level: Error
Source: Msiinstaller
Event ID: 11705

"Product: Java SE Development Kit 8 Update 60 (64-bit) -- Error 1705.A previous installation for this product is in progress.  You must undo the changes made by that installation to continue.  Do you want to undo those changes?"

XML error info: 

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="MsiInstaller" /> 
  <EventID Qualifiers="0">11705</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-11-03T14:07:47.000000000Z" /> 
  <EventRecordID>4170</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>az-prod-bpm01.prod.napower.com</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data>Product: Java SE Development Kit 8 Update 60 (64-bit) -- Error 1705.A previous installation for this product is in progress. You must undo the changes made by that installation to continue. Do you want to undo those changes?</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data /> 
  <Binary>7B36344133413446342D423739322D313144362D413738412D3030423044303138303630307D</Binary> 
  </EventData>
  </Event>
```

**Comment by glennmate** [comment]
So after some more thorough reading of the cookbook I may have found the problem. The *default['java']['windows']['package_name']* attribute may be set incorrectly. I am making a change on my end and testing in test-kitchen to validate now. I will advise if this is the fix and update this issue accordingly.

**Comment by erichelgeson** [comment]
@glennmate thanks for looking into this. Be happy to review a PR if you find a fix.

**Comment by glennmate** [comment]
@erichelgeson No issues with the cookbook provided here in this repo. Problem was with the syntax and pulling bad info from the registry. I updated my entry to the below:

```default['java']['windows']['package_name'] = "Java 8 Update 60 (64-bit)"```

And the issue resolved. I'd hazard to guess that open issue #297  is likely similar to this. This issue is closed.
