### ISSUE TITLE
Java JCE Installation Error

### ISSUE THREAD

**Issue by st-isidore-de-seville** [agileorbit-cookbooks/java#320]
Ohai!  I would normally submit a PR for this kind of thing but did not know the best way to handle it.  Long story short, when I go to install the JCE policy files for Java 8, Java 8 is installed `/usr/lib/jvm/java` and the JCE policy files are installed `/usr/lib/jvm/java/jre/lib/security` with symlinks to the JCE policy files being installed in their default location at `/opt/java_jce/8/`  The issue is that the JCE files are installed at `node['java']['oracle']['jce']['home']`.  The Chef resource appropriate creates the directory recursively but only sets the permissions of the directory at the lowest level leaf (https://github.com/agileorbit-cookbooks/java/blob/v1.37.0/recipes/oracle_jce.rb#L36-L39) on the `/opt/java_jce/8` directory but the `/opt/java_jce` directory that is created does not have world readable permissions.  On my system, the permissions are created for 740.  What this means is that a service running as non-root cannot resolve the symlinks to the JCE policy files because parts of the file path are not traversable by the world.  

What would be the best way to handle this so that all directories that are created recursively get the proper permissions to handle the symlink?  

Hopefully this makes sense and I can clarify if needed!

Thanks Chefs!

**Comment by sdarwin** [comment]
> On my system, the permissions are created for 740.
The permissions in the cookbook recipe you linked to show mode '0755', right?   
In testing it seems to correctly be 0755 on Ubuntu.   
Which operating system do you have?  What are the permissions on just /opt? 
If you launch brand new instances with test kitchen can you re-confirm the results?

**Comment by st-isidore-de-seville** [comment]
I was testing using CentOS 6/7 and I can confirm I am still having the issue.  Using test-kitchen opt is getting 755 permissions.  I think this is a umask problem per OS and probably has to explicitly be stated in the cookbook to ensure non-root users can get access to this directory.

**Comment by sdarwin** [comment]
"On my system, the permissions are created for 740."   740 could be a problem.   However, here are the permissions I see on test-kitchen CentOS7 (which you could also run).   Everything is at least globally readable.   There is not a 0 permission.     Maybe your proprietary cookbook is doing something to alter permissions.    This test is only with the java cookbook.  Observe:

kitchen converge oracle-8-centos-71

# cd java_jce/
[root@oracle-8-centos-71 java_jce]# ls -al
total 0
drwxr-xr-x. 3 root root 14 Feb  9 19:49 .
drwxr-xr-x. 6 root root 95 Feb  9 19:49 ..
drwxr-xr-x. 2 root root 56 Feb  9 19:49 8
[root@oracle-8-centos-71 java_jce]# cd 8/
[root@oracle-8-centos-71 8]# ls -al
total 8
drwxr-xr-x. 2 root root   56 Feb  9 19:49 .
drwxr-xr-x. 3 root root   14 Feb  9 19:49 ..
-rw-rw-r--. 1 root root 3035 Dec 20  2013 local_policy.jar
-rw-rw-r--. 1 root root 3023 Dec 20  2013 US_export_policy.jar

# ls -al /usr/lib/jvm/jdk1.8.0_65/jre/lib/security/
total 152
drwxr-xr-x.  2 root root  4096 Feb  9 19:49 .
drwxr-xr-x. 15 root root  4096 Oct  7 00:29 ..
...
lrwxrwxrwx.  1 root root    32 Feb  9 19:49 local_policy.jar -> /opt/java_jce/8/local_policy.jar
lrwxrwxrwx.  1 root root    36 Feb  9 19:49 US_export_policy.jar -> /opt/java_jce/8/US_export_policy.jar

**Comment by erichelgeson** [comment]
@sdarwin is correct, if you have a custom umask, you'll have to address that in a wrapper cookbook, thanks!
