### ISSUE TITLE
mulitple java versions

### ISSUE THREAD

**Issue by Raboo** [agileorbit-cookbooks/java#322]
Have you considered implementing a way to install multiple versions of java on same node, but having only one as default?

**Comment by erichelgeson** [comment]
You can use the `java_ark` resource in this cookbook as shown here https://github.com/erichelgeson/jenkins-chef-dsl/blob/master/recipes/build-jdks.rb#L17-L32 to have multiple JDKs. If you also want a default one just run the default recipe with the node attributes you want as the default.

**Comment by Raboo** [comment]
Ok I will try with java_ark, I'll close this issue for now.

Thanks
