### ISSUE TITLE
Java install failing on Windows since 1.37

### ISSUE THREAD

**Issue by ggascoigne** [agileorbit-cookbooks/java#325]
Looks like 1.37 found its way to the supermarket yesterday.

Since then I'm getting errors installing java.  

[2016-01-11T16:43:29-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Java 8 Update 51 (64-bit)] (java::windows line 80) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127], but received '-80'
---- Begin output of start "" /wait "c:\windows\temp\chef_temp\local-mode-cache\cache\jre-windows-x64-1.8.0.51.exe"   /s INSTALLDIR="C:\Program Files\Java\jre1.8.0_51" /INSTALLDIRPUBJRE="" & exit %%%%ERRORLEVEL%%%% ----
STDOUT:
STDERR:
---- End output of start "" /wait "c:\windows\temp\chef_temp\local-mode-cache\cache\jre-windows-x64-1.8.0.51.exe"   /s INSTALLDIR="C:\Program Files\Java\jre1.8.0_51" /INSTALLDIRPUBJRE="" & exit %%%%ERRORLEVEL%%%% ----

Reverting back to version 1.36.0 works perfectly.

**Comment by erichelgeson** [comment]
This was the only change was this - https://github.com/agileorbit-cookbooks/java/commit/6f0fad78858425a402866b3555a599b124e613a7#diff-4f50112fe9c68776e2852d8d5e6b887cR75

It looks like this `if` is bad https://github.com/agileorbit-cookbooks/java/commit/6f0fad78858425a402866b3555a599b124e613a7#diff-4f50112fe9c68776e2852d8d5e6b887cR75

@scottresnik any thoughts on that?

**Comment by scottresnik** [comment]
Looks like the nil default being set for the public jre location is breaking the attribute existence check. @erichelgeson would you prefer to have the default removed, or augment the if to check for the attribute existence, and it being not nil?

**Comment by erichelgeson** [comment]
Ahh I see, the `.attribute?()` is nil safe but even the existence of the key (being nil) causes it to be true.

I think the second option (augment to check existence and not nil) would be the least surprised. Incase anyone ever wanted to unset that option they could easily do it by setting it to nil

**Comment by scottresnik** [comment]
I agree.  I'll submit a new pull request.

**Comment by erichelgeson** [comment]
v1.38 pushed to supermarket with the fix. Thanks @scottresnik 

@ggascoigne - can you re-test and close (sorry i have no windows machines to test with)

**Comment by rhargreaves** [comment]
Looks like there's a `:wq` file in the root of the package for 1.38. As a result it's failing to sync on Windows Chef:

```
  ==============================================================================
==
  Error Syncing Cookbooks:
  ==============================================================================
==

  Unexpected Error:
  -----------------
  Chef::Exceptions::FileNotFound: Cannot find c:/chef/cache/cookbooks/java/:wq f
or cookbooks/java/:wq!
```

**Comment by erichelgeson** [comment]
Was editing in vim and accidentally wrote that file out, ha, it has been re-uploaded without it.

**Comment by rhargreaves** [comment]
Heh, I thought Vim had some part in it... :) Thanks for speedy fix!
