### ISSUE TITLE
[Request] Tomcat cookbook is changing my Java versions on CentOS 6.  Best way to work around this problem?

### ISSUE THREAD

**Issue by Joseph-R** [agileorbit-cookbooks/java#327]
Related to https://github.com/chef-cookbooks/tomcat/issues/198.

**Sequence:**
1. Install Java with this cookbook.  Java version is set correctly.
2. Install Tomcat with https://github.com/chef-cookbooks/tomcat.  Java version is set back to CentOS 6 default.

Specific CLI output from some troubleshooting posted [here](https://gist.github.com/Joseph-R/62978744999b8204dd6b).

I've opened [an issue](https://github.com/chef-cookbooks/tomcat/issues/198) with the Tomcat cookbook and looked through their source code.  I can't figure out what the source of this behavior is in their code.  

**Disclaimer:** I'm a total novice when it comes to either Java or Tomcat.  We're a Ruby shop.  So please bear with me if this problem or the answer is overly obvious.  I'm a fish out of water here.

Does anybody have any idea what is causing this?  What is the best way to work around it?

**Comment by erichelgeson** [comment]
Resolved in related issue
