### ISSUE TITLE
Issue with JAVA_HOME.

### ISSUE THREAD

**Issue by yurylevin** [agileorbit-cookbooks/java#335]
Hi,

Line of code https://github.com/agileorbit-cookbooks/java/blob/master/recipes/set_java_home.rb#L19 is being executed from time to time again. Can you help us to find out if you have proper condition for this block or variable isn't set up properly?

I use CentOS 7 with latest Chef client.

Thanks,
Yury.

**Comment by mhedgpeth** [comment]
In other words, the cookbook isn't idempotent on a centos box; the env is updated even though the rest of the system doesn't appear to be changing.

**Comment by erichelgeson** [comment]
This is no longer an issue, using the test config `oracle-8-centos-71`
First run:
```
       Chef Client finished, 14/20 resources updated in 04 minutes 24 seconds
       Finished converging <oracle-8-centos-71> (5m3.74s).
```
Second run:
```
       Chef Client finished, 0/17 resources updated in 06 seconds
       Finished converging <oracle-8-centos-71> (0m11.14s).
```
