### ISSUE TITLE
BIG request: refactor entire cookbook into resources

### ISSUE THREAD

**Issue by eric-tucker** [agileorbit-cookbooks/java#350]
This is the way to go now for community cookbooks.  I think this cookbook is suffering from the same issues the Tomcat cookbook did: attribute overwhelming.

**Comment by erichelgeson** [comment]
Have you taken a look at the `jdk_ark` this cookbook provides?

Usage as so - https://github.com/erichelgeson/jenkins-chef-dsl/blob/master/recipes/build-jdks.rb

**Comment by erichelgeson** [comment]
In addition you may want to take a look at this cookbook https://supermarket.chef.io/cookbooks/java_se
