### ISSUE TITLE
JAVA_HOME not set on systems with restrictive umask

### ISSUE THREAD

**Issue by ge1st** [agileorbit-cookbooks/java#359]
Hi guys,

Removing [this line](https://github.com/agileorbit-cookbooks/java/commit/29254b25458bff22c6b79eaa48bbac4ecdac68ee#diff-4b09f118ed8cafe9981df8a7d87368a2L32) breaks setting `JAVA_HOME` on systems which have a restrictive umask. For instance our setup prevents world-readable by default and users weren't getting `JAVA_HOME` set.

Mind adding it back?

**Comment by erichelgeson** [comment]
Good catch. I'll push up a new release by end of week with this fix.
