### ISSUE TITLE
Options for Java_home and alternatives

### ISSUE THREAD

**Issue by srirammageswaran** [agileorbit-cookbooks/java#361]
Hi ,

Can we have separate attributes to enable JAVA_HOME and run alternatives to put java in path. I am thinking of to support multi versions of java as i have two diff applications running in different versions of java.

Thanks ,
Sriram Mageswaran.

**Comment by erichelgeson** [comment]
If you'd like two versions on the same system you might want to look at using the `jdk_ark` resource provided by this cookbook, and then set java_home individually for each app. Something like https://github.com/erichelgeson/jenkins-chef-dsl/blob/master/recipes/build-jdks.rb#L17-L32

**Comment by erichelgeson** [comment]
Please let me know if you have any questions.
