### ISSUE TITLE
Oracle java 8 source is re-downloaded even though package is installed

### ISSUE THREAD

**Issue by eyalzek** [agileorbit-cookbooks/java#364]
I have made a vagrant box provisioned with chef to install oracle java 8. This installation is usually the step that takes the longest in our recipes and also times out in many cases.
The problem is that it still tries to download the tarball even though the package is installed. From what I can understand from the cookbook code, it's checking to see if the tarball exists in the chef cache directory in order to determine if it should be installed or not (obviously I might be wrong about that).
Does it not make more sense to check if the package itself is installed?
Is there a way for me to avoid it re-downloading the source with the current version of the cookbook somehow?

**Comment by erichelgeson** [comment]
If the checksums of the file matches it shouldn't re-download the file. I just verified this as well on `oracle-8-centos-71` kitchen test - the first converge I saw the network traffic to oracle, the second took 11 seconds and no network traffic.
