### ISSUE TITLE
JCE file installation failed to link files

### ISSUE THREAD

**Issue by rwildgrube** [agileorbit-cookbooks/java#376]
For some reason the JCE fails to link the files. The files are download and extracted correctly and they are there but for some reason the link process fails. Any ideas?

          ================================================================================
           Error executing action `create` on resource 'link[/usr/java/latest/jre/lib/security/local_policy.jar]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory @ rb_file_s_symlink - (/opt/java_jce/8/local_policy.jar, /usr/java/latest/jre/lib/security/local_policy.jar)

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/java/recipes/oracle_jce.rb

            97:     link jar_path do
            98:       to ::File.join(node['java']['oracle']['jce']['home'], jdk_version, jar)
            99:     end
           100:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/java/recipes/oracle_jce.rb:97:in `block in from_file'

           link("/usr/java/latest/jre/lib/security/local_policy.jar") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             to "/opt/java_jce/8/local_policy.jar"
             link_type :symbolic
             target_file "/usr/java/latest/jre/lib/security/local_policy.jar"
             declared_type :link
             cookbook_name "java"
             recipe_name "oracle_jce"
           end

**Comment by erichelgeson** [comment]
Can you try to create the symlink manually and see if there is a permissions or mount issue? I see your running in test kitchen, sometimes the shared folders mounted wont allow symlinks.
