### ISSUE TITLE
Oracle Java 8 JDK download link no longer works

### ISSUE THREAD

**Issue by danielwray** [agileorbit-cookbooks/java#379]
Hi,

The attribute value for `default['java']['jdk']['8']['x86_64']['url']` now redirects to the following Oracle page https://www.oracle.com/splash/edelivery/index.html when accessing from the UK.

This causes the following error:

`==> default: [2016-11-10T15:55:58+00:00] ERROR: java_ark[jdk] (java::oracle line 59) had an error: SystemExit: exit`

Is there a plan to update the link, or a known good URL endpoint that we can be used to override the attribute value?

**Comment by mrmarbury** [comment]
I have the same problem with JDK 7. So currently we are not able to bootstrap new machines that require java

**Comment by erichelgeson** [comment]
This looks to be an issue with oracle:
```
HTTP request sent, awaiting response... 503 Service Unavailable
```

The default Oracle is provided for convenience but Oracle does change things/isn't reliable.

To avoid this please use a copy that you host yourself on S3 or Artifactory to take availability into your own hands.

**Comment by bhare** [comment]
> The attribute value for default['java']['jdk']['8']['x86_64']['url'] now redirects to the following Oracle page https://www.oracle.com/splash/edelivery/index.html when accessing from the UK.

I'm getting redirected similarly, both from the US and from Ireland.

**Comment by joshzitting** [comment]
we are seeing this too.. even when you try to download it from here. http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u75-oth-JPR and try to get the jdk it still fails. so either it is an oracle site issue or they are going to start charging for java. ;)

**Comment by mrballcb** [comment]
Unsure if it's a problem or if it's intentional. It worked just fine yesterday when we deployed to test hosts across APAC, EMEA, and NA with no issues.  Today it is not working from any region.

**Comment by erichelgeson** [comment]
Locking this issue since oracle is having some sort of issue or policy change. When thats resolved I'll post here or release an updated version and comment/close this issue.

The solution is to host your binaries somewhere you control, possibly grabbing them off a previously provisioned machine.

**Comment by erichelgeson** [comment]
Looks like Oracle is behaving as it was before today. Take this opportunity to host the JDK on your network.
