### ISSUE TITLE
No such cookbook: windows

### ISSUE THREAD

**Issue by jeusdi** [agileorbit-cookbooks/java#400]
I'm getting this error when I'm trying to provion my vm using vagrant and chef:

    ==> default: ====================================
    ==> default: Error Resolving Cookbooks for Run List:
    ==> default: ====================================
    ==> default:
    ==> default: Missing Cookbooks:
    ==> default: ------------------
    ==> default: No such cookbook: windows
    ==> default:
    ==> default: Expanded Run List:
    ==> default: ------------------
    ==> default: * java
    ==> default:
    ==> default: Platform:
    ==> default: ---------
    ==> default: x86_64-linux
    ==> default:

My vagrant structure is:

    VagrantFile
    ├───chef
    │   ├───cookbooks
    │   │   ├───apt
    │   │   ├───java
    │   ├───roles
    │   │   ├───java-dev-workstation.rb

`Vagrantfile` content is:

    Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
      config.vm.provision "chef_solo" do |chef|
        chef.roles_path = "chef/roles"
        chef.cookbooks_path = "chef/cookbooks"
        chef.add_role "java-dev-workstation"
      end
    end

And `java-dev-workstation.rb`:
 
    name "java-dev-workstation"
 
    default_attributes( 
      # Because it's Oracle, we need to agree to the terms and conditions.
      :java => { 
        :install_flavor => 'oracle',
        :jdk_version => '8',
        :accept_license_agreement => true,
        :oracle => { "accept_oracle_download_terms" => true } 
      }
     
    )
     
    run_list(
      "recipe[java]"
    )

Any ideas?

**Comment by erichelgeson** [comment]
Hi - It looks like you do not have the windows cookbook - it is a dependency of this cookbook. You can use Berks to resolve your cookbook deps or pull them down manually.
