### ISSUE TITLE
How to install java 8 using berkshelf

### ISSUE THREAD

**Issue by jeusdi** [agileorbit-cookbooks/java#401]
My berkshelf folder structure is like:

    │   Berksfile
    │   Berksfile.lock
    │   chefignore
    │   knife.rb
    │   living.pem
    │   metadata.rb
    ├───recipes
    │       default.rb
    │       elasticsearch.rb
    │       java.rb

The content of each `recipe.rb` is:

`default.rb` content file:

    include_recipe 'berk::java'
    include_recipe 'berk::elasticsearch'

`java.rb` content file:

    include_recipe 'java'
    node.default['java']['install_flavor'] = 'oracle'
    node.default['java']['jdk_version'] = '8'
    node.default['java']['oracle']['accept_oracle_download_terms'] = true

`elasticsearch.rb` content file:

    include_recipe 'elasticsearch'
    
    elasticsearch_user 'elasticsearch' do
      username 'elasticsearch'
      groupname 'elasticsearch'
      shell '/bin/bash'
      comment 'Elasticsearch User'
    
      action :create
    end
    
    elasticsearch_install 'my_es_installation' do
      type 'package' # type of install
      version '5.2.0'
      action :install # could be :remove as well
    end

    ...

I would like to change java settings in order to use java 8 of oracle. I know that probably it seems a very straightforward question, nevertheless, I've really stuck on that issue.

I've tried to add these lines in `java.rb`:

    node.default['java']['install_flavor'] = 'oracle'
    node.default['java']['jdk_version'] = '8'
    node.default['java']['oracle']['accept_oracle_download_terms'] = true

And also I've tried:

    node.override['java']['install_flavor'] = 'oracle'
    node.override['java']['jdk_version'] = '8'
    node.override['java']['oracle']['accept_oracle_download_terms'] = true

Nevertheless, Java 6 is installed:

    ==> default:   * log[jdk-version-changed] action nothing (skipped due to action :nothing)
    ==> default: Recipe: java::openjdk
    ==> default:   * yum_package[java-1.6.0-openjdk] action install
    ==> default: [2017-02-21T15:10:33+00:00] INFO: yum_package[java-1.6.0-openjdk] installing java-1.6.0-openjdk-1.6.0.41-1.13.13.1.el7_3 from updates repository

Any ideas?

**Comment by erichelgeson** [comment]
Hi, please use stackoverflow, slack, or other forms for usage questions.
