### ISSUE TITLE
JRE_HOME

### ISSUE THREAD

**Issue by skylerto** [agileorbit-cookbooks/java#404]
I ran into an issue which lead to the need of setting JRE_HOME, would it be desirable to set `JRE_HOME` within this cookbook, perhaps as a recipe?

**Comment by erichelgeson** [comment]
I think this is fine to be left to a wrapper cookbook - I dont find it a common use case software needs JRE_HOME.

**Comment by skylerto** [comment]
@erichelgeson thanks for the feedback.

Anything that needs libs not to be modified or increased security properties. Here's our use case, we're using bouncycastle for pgp (de/en)cryption, including it as a maven dependency modifies the signature of the jar and renders it useless. Leading us to need `JRE_HOME` set, and the original jar to be located in `JRE_HOME/lib`.
