### ISSUE TITLE
Don't run `apt update` in common cookbooks

### ISSUE THREAD

**Issue by grv87** [agileorbit-cookbooks/java#406]
See Chef developer's opinion here: https://github.com/chef-cookbooks/runit/pull/214#issuecomment-286858834:
> Apt updates are something that need to be managed by the consumer of the cookbook themselves. We end up with multiple cookbooks each trying to do apt-updates and it's a bit of a mess.

**Comment by erichelgeson** [comment]
I am a centos user mostly - so dont run the apt version often. Where is apt-get update being ran in this cookbook? I know we add a ppa (which I believe does require an update before we can use packages from it)

**Comment by grv87** [comment]
Here: https://github.com/agileorbit-cookbooks/java/blob/master/recipes/openjdk.rb#L46

**Comment by erichelgeson** [comment]
I dont see how we can add the ppa and not do an update. If there is a way to do this please open a PR with a proposal.

**Comment by grv87** [comment]
According to [Chef documentation](https://docs.chef.io/resource_apt_repository.html):

> Adding a new repository will update apt package cache immediately.

So, it should be unnecessary to run another update manually. That line of code is redundant. I could make PR if it would help.

**Comment by erichelgeson** [comment]
Sounds good - if it passes the kitchen tests I'll merge it in.
