### ISSUE TITLE
Unauthorized Request

### ISSUE THREAD

**Issue by mattwuenschel** [agileorbit-cookbooks/java#409]
Fetching the link provided with the attribute ['java']['jdk']['7']['x86_64']['url'] returns unauthorized request. *http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz*

[2017-03-27T19:15:50+00:00] FATAL: Failed to extract file jdk-7u75-linux-x64.tar.gz!
ESC[0m
================================================================================ESC[0m
ESC[31mError executing action `install` on resource 'java_ark[jdk]'ESC[0m
================================================================================ESC[0m

ESC[0mSystemExitESC[0m
----------ESC[0m
exitESC[0m

ESC[0mCookbook Trace:ESC[0m
---------------ESC[0m
/var/chef/cookbooks/java/providers/ark.rb:167:in `block (2 levels) in class_from_file'
ESC[0m/var/chef/cookbooks/java/providers/ark.rb:144:in `block in class_from_file'
ESC[0m/var/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'ESC[0m

ESC[0mResource Declaration:ESC[0m
---------------------ESC[0m
# In /var/chef/cookbooks/java/recipes/oracle.rb
ESC[0m
ESC[0m 59: java_ark 'jdk' do
ESC[0m 60:   url tarball_url
ESC[0m 61:   default node['java']['set_default']
ESC[0m 62:   checksum tarball_checksum
ESC[0m 63:   app_home java_home
ESC[0m 64:   bin_cmds bin_cmds
ESC[0m 65:   alternatives_priority node['java']['alternatives_priority']
ESC[0m 66:   retries node['java']['ark_retries']
ESC[0m 67:   retry_delay node['java']['ark_retry_delay']
ESC[0m 68:   connect_timeout node['java']['ark_timeout']
ESC[0m 69:   use_alt_suffix node['java']['use_alt_suffix']
ESC[0m 70:   reset_alternatives node['java']['reset_alternatives']
ESC[0m 71:   download_timeout node['java']['ark_download_timeout']
ESC[0m 72:   proxy node['java']['ark_proxy']
ESC[0m 73:   action :install
ESC[0m 74:   notifies :write, 'log[jdk-version-changed]', :immediately
ESC[0m 75: end
ESC[0m 76:
ESC[0m 77: if node['java']['set_default'] && platform_family?('debian')
ESC[0m 78:   include_recipe 'java::default_java_symlink'
ESC[0m 79: end
ESC[0m 80:
ESC[0m
ESC[0mCompiled Resource:ESC[0m
------------------ESC[0m
# Declared in /var/chef/cookbooks/java/recipes/oracle.rb:59:in `from_file'
ESC[0m
ESC[0mjava_ark("jdk") do
ESC[0m  action [:install]
ESC[0m  supports {:report=>true, :exception=>true}
ESC[0m  retries 0
ESC[0m  retry_delay 2
ESC[0m  default_guard_interpreter :default
ESC[0m  declared_type :java_ark
ESC[0m  cookbook_name :java
ESC[0m  recipe_name "oracle"
ESC[0m  url "http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz"
ESC[0m  default true

**Comment by mattwuenschel** [comment]
This appears to have resolved itself as the link works now.

**Comment by erichelgeson** [comment]
Ensure you host artifacts locally so you're not at the whim of Oracle's website.
