### ISSUE TITLE
FATAL: No download url set for java installer. (Windows)

### ISSUE THREAD

**Issue by osnapitseric** [agileorbit-cookbooks/java#416]
Hi, I'm very new to this. I'm getting an error saying there isn't a download URL for the the java installer. I'm running this on a Window2012r2. I have "depends 'java'" in my metadata and "include_recipe 'java'" in my default recipe.

Do I need to specify a download url?  If so, could I get an example how it would be written out in Chef? Per the documentation it said to just put include_recipe 'java'.

[2017-04-13T23:07:26+00:00] FATAL: No download url set for java installer.

       ================================================================================
       Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/struxure-cookbook/recipes/default.rb
       ================================================================================

       URI::InvalidURIError
       --------------------
       bad URI(is not URI?):

**Comment by erichelgeson** [comment]
Just set the attribute `node['java']['windows']['url']` to a URL for the installer.
