### ISSUE TITLE
Oracle Java 6/7 fails

### ISSUE THREAD

**Issue by hulu1522** [agileorbit-cookbooks/java#427]
We had to change the URLs and host our own files because Oracle is making every download of Java 6/7 only accessible by a logged in user.  Your cookbook is failing on those versions right now.

**Comment by erichelgeson** [comment]
Yes, oracle changes this frequently. You should host your own java dists. See the top of the README and the 1.50 changelog https://github.com/agileorbit-cookbooks/java/blob/master/CHANGELOG.md#v1500---05242017
