### ISSUE TITLE
java gets installed with 0 size

### ISSUE THREAD

**Issue by raushan9108** [agileorbit-cookbooks/java#429]
Hi there,

I am using java cookbook latest downloaded form master branch
On few of my ubuntu servers, this cookbook is working fine and there is no problem at all but on few, it is failing continuously with no errors and exceptions in chef log. There is no difference in server settings. I am installing java on download from oracle directly. i debugged the issue and found that java gets installed properly but of 0 size. I compared the settings with the one of working servers and found everything intact. It also points to correct java installed in the system.  Can anyone please help me here? Thanks in advance.

Few settings in attributes/default.rb:
 
default['java']['oracle']['accept_oracle_download_terms'] = true
default['java']['java_home'] = "/usr/lib/jvm/default-java"

default['java']['jdk']['8']['x86_64']['url'] = 'https://edelivery.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz'
default['java']['jdk']['8']['x86_64']['checksum'] = '62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236'

root@ip-10-x-x-x:/var/chef/cache/cookbooks/java# du -sh /usr/lib/jvm/default-java/bin/java
0	/usr/lib/jvm/default-java/bin/java

root@ip-10-x-x-x:/home/xxxxxx# sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      auto mode
* 1            /usr/lib/jvm/default-java/bin/java               1062      manual mode
  2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode

Thanks,
Raushan

**Comment by raushan9108** [comment]
Every file in /usr/lib/jvm/default-java/bin directory is of 0 KB. Any help please?

**Comment by erichelgeson** [comment]
You'll need to provide more information. if it works on one machine but not another there must be something different in the environment affecting this. Try to turn logging all the way up. Also remove the jdk from the chef cache and allow it to re-download (or better yet, host it internally on a file server or S3)

**Comment by raushan9108** [comment]
Hi erichelgeson,

Thank you for the reply. This was temporary issue and got resolved automatically. I don't know understand the reason. But, it seems that the problem was either with the downloaded tarball or its extraction. 

Moving further, I want know keep this on s3. So anyone could you please suggest the possible changes?
I believe we need to change

**Comment by erichelgeson** [comment]
See https://github.com/agileorbit-cookbooks/java#production-deployment-with-oracle-java

Thanks
